@host = 10.252.26.240:8080
@host1 = 10.252.31.16:5000

### Login

# @name login
POST http://{{host}}/h2-bim-project/project2/login HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "account":"wmz",
    "isRemember":true,
    "password":"733d7be2196ff70efaf6913fc8bdcabf"
}

###login1

POST http://{{host1}}/api/User/Login HTTP/1.1
Content-Type: application/json

{
    "userName":"test",
    "password":"111111"
}


